# Importing numpy library

In [1]:
import numpy as np

# Creating numpy arrays

# One dimensional arrays

In [2]:
L=[23,33,35,56,67,78]
arr=np.array(L)
print(arr)

[23 33 35 56 67 78]


In [3]:
arr

array([23, 33, 35, 56, 67, 78])

# Two dimensional arrays

In [4]:
L=[[12,22,23],[56,54,77]]
arr=np.array(L)
print(arr)

[[12 22 23]
 [56 54 77]]


In [5]:
arr

array([[12, 22, 23],
       [56, 54, 77]])

# Array properties

In [6]:
arr1=np.array([23,33,35,56,67,78])
arr2=np.array([[12,22,23],[56,54,77]])

In [7]:
arr1

array([23, 33, 35, 56, 67, 78])

In [8]:
arr2

array([[12, 22, 23],
       [56, 54, 77]])

# Shape of the array

In [9]:
print(arr1.shape)
print(arr2.shape)

(6,)
(2, 3)


# Dimensions of the array

In [10]:
print(arr1.ndim)
print(arr2.ndim)

1
2


# Data type inside arrays

In [11]:
print(arr1.dtype)
print(arr2.dtype)

int32
int32


# Size of arrays

In [12]:
print(arr1.size)
print(arr2.size)

6
6


# Special arrays

# Null array

In [13]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
b=np.zeros((3,3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Ones array

In [15]:
a=np.ones(20)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
b=np.ones((5,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Identity matrix

In [17]:
I3=np.eye(3)
print(I3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Simulating random integers

In [18]:
r=np.random.randint(2,8) #One random integer from 2 to 8

In [19]:
r

4

In [20]:
r=np.random.randint(2,8,10) #10 random integers from 2 to 8

In [21]:
r

array([2, 6, 2, 3, 3, 7, 3, 4, 7, 3])

# Simulating random floats from 0 to 1

In [22]:
r=np.random.random(5)

In [23]:
r

array([0.61137111, 0.67125064, 0.12821443, 0.51479995, 0.80780689])

In [24]:
r=np.random.random((5,5))

In [25]:
r

array([[0.79180125, 0.24705266, 0.00990013, 0.89888192, 0.89751506],
       [0.86574371, 0.07442892, 0.16804242, 0.45352123, 0.13654964],
       [0.44112076, 0.2998447 , 0.21958022, 0.26185555, 0.85814004],
       [0.02016033, 0.82784135, 0.38094173, 0.82990084, 0.23007408],
       [0.69007785, 0.89695573, 0.9417007 , 0.748662  , 0.3674867 ]])

# Simulating random floats from standard normal distribution

In [26]:
r=np.random.randn(10)

In [27]:
r

array([ 0.08805111,  0.3963974 ,  0.31434471,  2.93454512,  0.74311956,
        0.26796766, -1.83129744,  0.6586675 , -0.27352593, -0.0383923 ])

In [28]:
r=np.random.randn(3,3)

In [29]:
r

array([[-0.17034571, -0.65104964, -0.36328228],
       [ 1.24571524, -0.54127275,  1.55958281],
       [ 0.99025215,  0.17295969,  0.90552233]])

# Simulating data from probability distributions

# Normal distribution

In [30]:
r=np.random.normal(50,5,4) #4 random values from a normal distribution with mean 50 and standard deviation 5

In [31]:
r

array([54.57264439, 44.65264004, 50.87078731, 39.67120809])

In [32]:
r=np.random.normal(50,5,(4,4))

In [33]:
r

array([[44.60543388, 40.31635676, 51.11305565, 43.42294919],
       [47.84170306, 49.54310321, 52.85899464, 42.48294551],
       [51.67990493, 55.46277233, 54.84861391, 57.49485868],
       [56.58284842, 49.22961379, 47.84663515, 57.97129371]])

# Uniform distribution

In [34]:
r=np.random.uniform(10,20,5)

In [35]:
r

array([19.00755161, 15.93920718, 13.1350319 , 18.41674919, 11.88593802])

In [36]:
r=np.random.uniform(10,20,(5,5))

In [37]:
r

array([[18.30770765, 14.81656595, 13.5431284 , 18.8535427 , 16.6831832 ],
       [12.16937541, 16.86739071, 15.66947572, 17.75458259, 14.24981517],
       [12.52338178, 19.98040681, 18.30361661, 14.49774745, 18.93250109],
       [16.38957576, 16.97838255, 16.61034418, 15.87375434, 19.72826284],
       [19.14768313, 16.4781066 , 15.64857987, 15.83218007, 11.94067217]])

# Generating sequence

# arange function with single dimension

In [38]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
arr=np.arange(3,10)

In [40]:
arr

array([3, 4, 5, 6, 7, 8, 9])

# Changing the shape of the sequence array

In [41]:
arr=np.arange(20)
arr.shape=(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
arr=np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Indexing & slicing one dimensional numpy arrays

In [43]:
a=np.array([12,22,34,56,54,56])

In [44]:
a[0]

12

In [45]:
a[2]

34

In [46]:
a[-1]

56

In [47]:
a[2:5]

array([34, 56, 54])

In [48]:
a[3:]

array([56, 54, 56])

In [49]:
a[:3]

array([12, 22, 34])

In [50]:
a[::2]

array([12, 34, 54])

In [51]:
a[::-1]

array([56, 54, 56, 34, 22, 12])

# Indexing & slicing multi dimensional numpy arrays

In [52]:
b=np.array([[23,33,34,45,56],[23,33,34,56,54],[78,65,67,64,78]])
b

array([[23, 33, 34, 45, 56],
       [23, 33, 34, 56, 54],
       [78, 65, 67, 64, 78]])

In [53]:
b[0,3]

45

In [54]:
b[:2,1:4]

array([[33, 34, 45],
       [33, 34, 56]])

In [55]:
b[1,[2,4]]

array([34, 54])

# Numpy arrays are mutable

In [56]:
a=np.array([23,33,45,56,54])

In [57]:
a[0]=100

In [58]:
a

array([100,  33,  45,  56,  54])

# Array masking

In [59]:
a=np.array([34,45,33,23,45,67,65,78,21])

In [60]:
a>50

array([False, False, False, False, False,  True,  True,  True, False])

In [61]:
a[a>50]

array([67, 65, 78])

# Replacing existing values with new values

In [62]:
a=np.array([-23,34,-15,-22,56])

In [63]:
np.where(a>0)

(array([1, 4], dtype=int64),)

In [64]:
b=np.where(a>0,a,0)

In [65]:
b

array([ 0, 34,  0,  0, 56])

# Basic numpy functions

# numpy functions with scaler values

In [66]:
np.sin(12) #Trigonometry

-0.5365729180004349

In [67]:
np.log(10) #Log

2.302585092994046

In [68]:
np.power(4,2) #Power

16

In [69]:
np.exp(2) #Exponential values

7.38905609893065

In [70]:
np.round(34.567) #Rounding

35.0

# numpy functions with arrays

In [71]:
arr=np.array([34,33,21,25,56,32,44,78,12])

In [72]:
arr.min()

12

In [73]:
arr.max()

78

In [74]:
arr.mean()

37.22222222222222

In [75]:
arr.sort()
arr

array([12, 21, 25, 32, 33, 34, 44, 56, 78])

In [76]:
np.median(arr)

33.0

# Special numpy values

In [77]:
np.pi

3.141592653589793

In [78]:
np.e

2.718281828459045

In [79]:
np.inf

inf

In [80]:
np.NINF

-inf

In [81]:
np.nan

nan

# Stacking numpy arrays

# Vertical stacking & horizontal stacking

In [82]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [83]:
c=np.vstack((a,b))
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [84]:
d=np.hstack((a,b))
print(d)

[[3 4 5 2 3 7]
 [6 3 5 8 2 6]]


# Appending

In [85]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [86]:
c=np.append(a,b,axis=0)
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [87]:
d=np.append(a,b,axis=1)
print(d)

[[3 4 5 2 3 7]
 [6 3 5 8 2 6]]


# Concatenation

In [88]:
a=np.array([[3,4,5],[6,3,5]])
b=np.array([[2,3,7],[8,2,6]])

In [89]:
c=np.concatenate((a,b),axis=0)
print(c)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


In [90]:
d=np.concatenate((a,b),axis=0)
print(d)

[[3 4 5]
 [6 3 5]
 [2 3 7]
 [8 2 6]]


# Tiling

In [91]:
a=np.array([23,34])
b=np.tile(a,(1,2))
print(b)

[[23 34 23 34]]


In [92]:
a=np.array([23,34])
b=np.tile(a,(2,2))
print(b)

[[23 34 23 34]
 [23 34 23 34]]


In [93]:
a=np.array([[23,34],[56,54]])
b=np.tile(a,(1,2))
print(b)

[[23 34 23 34]
 [56 54 56 54]]


# Splitting arrays

# Horizontal splitting

In [94]:
a=np.random.random((4,4))
a

array([[0.07435012, 0.11670273, 0.47773019, 0.93682874],
       [0.23300694, 0.15293516, 0.64771157, 0.22359685],
       [0.0779587 , 0.96814964, 0.15262315, 0.0607329 ],
       [0.16087789, 0.57945626, 0.9672175 , 0.82908587]])

In [95]:
b=np.hsplit(a,2)
b

[array([[0.07435012, 0.11670273],
        [0.23300694, 0.15293516],
        [0.0779587 , 0.96814964],
        [0.16087789, 0.57945626]]),
 array([[0.47773019, 0.93682874],
        [0.64771157, 0.22359685],
        [0.15262315, 0.0607329 ],
        [0.9672175 , 0.82908587]])]

# Vertical spliiting

In [96]:
a=np.random.random((4,4))
a

array([[0.49935641, 0.72657731, 0.64025663, 0.66155411],
       [0.07087192, 0.98248534, 0.00679808, 0.07583775],
       [0.18140862, 0.75472511, 0.71291313, 0.99019375],
       [0.48112791, 0.95371078, 0.55753499, 0.72748352]])

In [97]:
b=np.vsplit(a,2)
b

[array([[0.49935641, 0.72657731, 0.64025663, 0.66155411],
        [0.07087192, 0.98248534, 0.00679808, 0.07583775]]),
 array([[0.18140862, 0.75472511, 0.71291313, 0.99019375],
        [0.48112791, 0.95371078, 0.55753499, 0.72748352]])]

# Rolling array elements

In [98]:
arr=np.array([1,2,3,4])
np.roll(arr,1)

array([4, 1, 2, 3])

In [99]:
arr=np.array([1,2,3,4])
np.roll(arr,2)

array([3, 4, 1, 2])

# Changing the data type

In [100]:
a=np.array([12.34,23.46,32.56])
b=a.astype(int)
b

array([12, 23, 32])

In [101]:
a=np.array(["12.34","23.46","32.56"])
b=a.astype(float)
b

array([12.34, 23.46, 32.56])

# Matrix operations

# Scaler multiplication

In [102]:
m1=np.array([[12,22,23],[45,43,33]])
3*m1

array([[ 36,  66,  69],
       [135, 129,  99]])

# Matrix addition & substraction

In [103]:
m1=np.array([10,20,30,40])
m2=np.array([30,40,50,60])

In [104]:
m1+m2

array([ 40,  60,  80, 100])

In [105]:
m1-m2

array([-20, -20, -20, -20])

In [106]:
m1=np.array([[12,22,23],[45,43,33]])
m2=np.array([[22,21,43],[46,23,13]])

In [107]:
m1+m2

array([[34, 43, 66],
       [91, 66, 46]])

In [108]:
m1-m2

array([[-10,   1, -20],
       [ -1,  20,  20]])

# Broadcasting

In [109]:
m1=np.array([10,20,30,40])

In [110]:
m1=m1+100
m1

array([110, 120, 130, 140])

# Matrix multiplication

In [111]:
m1=np.array([[12,23],[10,25]])
m2=np.array([[10,15],[5,15]])

In [112]:
m1*m2 #Hadamard product

array([[120, 345],
       [ 50, 375]])

In [113]:
np.dot(m1,m2)

array([[235, 525],
       [225, 525]])

In [114]:
m1.dot(m2)

array([[235, 525],
       [225, 525]])

In [115]:
np.dot(m2,m1)

array([[270, 605],
       [210, 490]])

In [116]:
m2.dot(m1)

array([[270, 605],
       [210, 490]])

# Trace of a matrix

In [117]:
m1=np.array([[12,23],[10,25]])

In [118]:
np.trace(m1)

37

# Diagonal elements of a square matrix

In [119]:
m1=np.array([[12,23],[10,25]])

In [120]:
np.diag(m1)

array([12, 25])

# Matrix transpose

In [121]:
m1=np.array([[12,23],[10,25]])
np.transpose(m1)

array([[12, 10],
       [23, 25]])

# Determinant of a matrix

In [122]:
m1=np.array([[12,23],[10,25]])
np.linalg.det(m1)

69.99999999999996

In [123]:
m2=np.array([[12,23,45],[10,25,15],[10,20,30]])
np.linalg.det(m2)

-299.99999999999943

# Inverse of a matrix

In [124]:
m1=np.array([[12,23],[10,25]])
np.linalg.inv(m1)

array([[ 0.35714286, -0.32857143],
       [-0.14285714,  0.17142857]])

In [125]:
m2=np.array([[12,23,45],[10,25,15],[10,20,30]])
np.linalg.inv(m2)

array([[-1.5       , -0.7       ,  2.6       ],
       [ 0.5       ,  0.3       , -0.9       ],
       [ 0.16666667,  0.03333333, -0.23333333]])

# Eigenvalues & normalized eigenvectors

In [126]:
m1=np.array([[12,23],[10,25]])

In [127]:
eigvals,eigvecs=np.linalg.eig(m1)

In [128]:
eigvals

array([ 2., 35.])

In [129]:
eigvecs

array([[-0.91707006, -0.70710678],
       [ 0.39872611, -0.70710678]])